name:                rubbishc
version:             0.1.0.0
github:              "sidsahay/rubbish-lang"
license:             BSD3
author:              "Siddharth Sahay"
maintainer:          "example@example.com"
copyright:           "2019 Siddharth Sahay"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sidsahay/rubbish-lang/rubbishc/README.md>

dependencies:
- base >= 4.7 && < 5
- mtl
- parsec

library:
  source-dirs: src

executables:
  rubbishc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rubbishc

tests:
  rubbishc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rubbishc
